/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21lZGlhL2RhZmZhL0t1bGlhaC9TZW1lc3RlciA0L1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXRhbi9NaW5nZ3UxMy9kZXBsb3ktZGVtby9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL21lZGlhL2RhZmZhL0t1bGlhaC9TZW1lc3RlciA0L1BlbXJvZ3JhbWFuIFdlYiBMYW5qdXRhbi9NaW5nZ3UxMy9kZXBsb3ktZGVtby9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
